app:
  title: Red Hat Developer Hub
  baseUrl: ${RHDH_RUNTIME_URL}
backend:
  auth:
    externalAccess:
      - type: legacy
        options:
          subject: legacy-default-config
          secret: "secret"
  baseUrl: ${RHDH_RUNTIME_URL}
  cors:
    origin: ${RHDH_RUNTIME_URL}
auth:
  environment: development
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true
